apiVersion: theodolite.com/v1
kind: execution
metadata:
  name: uc3-beam-samza-generic-linear-search-uc1-beam-samza
spec:
  benchmark: "uc3-beam-samza"
  load:
    loadType: "NumSensors"
    loadValues: [25000, 50000]
  resources:
    resourceType: "Instances"
    resourceValues: [1, 2, 3, 4, 5, 6]
  slos:
    - sloType: "generic"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties: 
        externalSloUrl: "http://localhost:80/evaluate-slope"
        queryAggregation: max
        repetitionAggregation: median
        operator: lte
        threshold: 1000
        promQLQuery: "sum by(job) (kafka_streams_stream_task_metrics_dropped_records_total>=0)"
  execution:
    strategy: "LinearSearch"
    duration: 120 # in seconds
    repetitions: 1
    loadGenerationDelay: 30 # in seconds
    restrictions:
      - "LowerBound"
  configOverrides:
    - patcher:
        type: "SchedulerNamePatcher"
        resource: "uc1-beam-samza-deployment.yaml"
      value: "random-scheduler" 