apiVersion: theodolite.com/v1
kind: execution
metadata:
  name: uc4-kstreams-lag-trend-binary-search-uc1-kstreams-400
spec:
  benchmark: "uc4-kstreams-400"
  load:
    loadType: "NumNestedGroups"
    loadValues: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  resources:
    resourceType: "Instances"
    resourceValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  slos:
    - sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties: 
        externalSloUrl: "http://localhost:80/evaluate-slope"
        threshold: 1000
        warmup: 0
  execution:
    strategy: "BinarySearch"
    duration: 60 # in seconds
    repetitions: 1
    loadGenerationDelay: 0 # in seconds
    restrictions: []
  configOverrides: []