apiVersion: theodolite.com/v1
kind: execution
metadata:
  name: uc4-beam-samza-lag-trend-binary-search-uc1-beam-samza
spec:
  benchmark: "uc4-beam-samza"
  load:
    loadType: "NumNestedGroups"
    loadValues: [25000, 50000, 75000, 100000, 125000, 150000]
  resources:
    resourceType: "Instances"
    resourceValues: [1, 2]
  slos:
    - sloType: "beam-samza"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        threshold: 2000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  execution:
    strategy: "BinarySearch"
    duration: 300 # in seconds
    repetitions: 1
    loadGenerationDelay: 30 # in seconds
    restrictions:
      - "LowerBound"
  configOverrides:
    - patcher:
        type: "SchedulerNamePatcher"
        resource: "uc1-beam-samza-deployment.yaml"
      value: "random-scheduler" 