apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc3-beam-samza-40
spec:
  infrastructure:
    afterActions: []
    beforeActions: []
    resources: []
  kafkaConfig:
    bootstrapServer: theodolite-kafka-kafka-bootstrap:9092
    topics:
    - name: input
      numPartitions: 40
      removeOnly: false
      replicationFactor: 1
    - name: output
      numPartitions: 40
      removeOnly: false
      replicationFactor: 1
    - name: .*samza.*
      numPartitions: 0
      removeOnly: true
      replicationFactor: 0
    - name: .*uc3-application.*
      numPartitions: 0
      removeOnly: true
      replicationFactor: 0
  loadGenerator:
    afterActions: []
    beforeActions: []
    resources:
    - configMap:
        files:
        - uc3-load-generator-deployment.yaml
        - uc3-load-generator-service.yaml
        name: benchmark-resources-uc3-load-generator
  loadTypes:
  - patchers:
    - properties:
        container: workload-generator
        variableName: NUM_SENSORS
      resource: uc3-load-generator-deployment.yaml
      type: EnvVarPatcher
    - properties:
        loadGenMaxRecords: "150000"
      resource: uc3-load-generator-deployment.yaml
      type: NumSensorsLoadGeneratorReplicaPatcher
    typeName: NumSensors
  name: ""
  resourceTypes:
  - patchers:
    - properties: {}
      resource: uc3-beam-samza-deployment.yaml
      type: ReplicaPatcher
    typeName: Instances
  sut:
    afterActions:
    - exec:
        command:
        - bash
        - -c
        - bin/zkCli.sh -server $ZOOKEEPER_SERVER deleteall /app-theodolite-uc3-application-1
        timeoutSeconds: 60
      selector:
        container: zookeeper-client
        pod:
          matchLabels:
            app: zookeeper-client
    beforeActions: []
    resources:
    - configMap:
        files:
        - uc3-beam-samza-deployment.yaml
        - beam-samza-service.yaml
        - service-monitor.yaml
        name: benchmark-resources-uc3-beam-samza
status:
  resourceSetsState: Pending
